import Head from "next/head";
import {
    AiFillTwitterCircle,
    AiFillLinkedin,
    AiFillYoutube,
    AiFillInstagram,
    AiFillGithub,
    AiFillCode,
    AiFillCodeSandboxCircle,
    AiFillBulb,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import profile from "../public/profile.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import Link from "next/link";

import Logo from "../components/icons/Logo";

export default function Home() {
    const [darkMode, setDarkMode] = useState(false);

    return (
        <div className={darkMode ? "dark" : ""}>
            <Head>
                <title>Raj Naik Dhulapkar - Full Stack Developer</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className=' bg-white dark:bg-gray-900 '>
                <section className='min-h-screen mt-[6rem]  w-[calc(100%-2rem)] m-auto'>
                    <nav className='p-3 px-5 mb-12 bg-stone-300 fixed left-4 top-2 -translate-x-2 w-[calc(100%-1rem)] z-50 rounded-lg  flex justify-between dark:text-white'>
                        {/* logo image  */}
                        <div className='flex w-10 h-10 items-center gap-4 '>
                            <Logo />
                        </div>
                        <div className='flex items-center'>
                            <div>
                                <BsFillMoonStarsFill
                                    onClick={() => setDarkMode(!darkMode)}
                                    className=' cursor-pointer text-2xl'
                                />
                            </div>
                            <div>
                                <a
                                    className='bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8'
                                    href='#'
                                >
                                    Menu
                                </a>
                            </div>
                        </div>
                    </nav>
                    <div className='text-center w-full'>
                        <h2 className='text-3xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl'>
                            Raj Naik Dhulapkar
                        </h2>
                        <h3 className='text-lg py-2 dark:text-white md:text-3xl'>
                            Web Dev • Learner • Builder
                        </h3>

                        <div className='mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-2 md:h-96 md:w-96'>
                            <Image alt='profile' src={profile} layout='fill' objectFit='cover' />
                        </div>
                        <p className='text-lg py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl'>
                            Building web wonders with code & passion 🚀 Exploring new tech frontiers
                            💡 Full Stack Developer 💻
                        </p>
                        <div className='text-5xl flex flex-wrap justify-center gap-16 py-3 text-gray-600 dark:text-gray-400'>
                            <a
                                target='_blank'
                                rel='noopener noreferrer'
                                href='https://twitter.com/RajNykDhulapkar'
                            >
                                <AiFillTwitterCircle />
                            </a>
                            <a
                                target='_blank'
                                rel='noopener noreferrer'
                                href='https://www.linkedin.com/in/rajnykdhulapkar/'
                            >
                                <AiFillLinkedin />
                            </a>
                            <a
                                target='_blank'
                                rel='noopener noreferrer'
                                href='https://www.youtube.com/channel/UCJoXR9HyrNQ2Xab62ElJcVQ'
                            >
                                <AiFillYoutube />
                            </a>
                            <a
                                target='_blank'
                                rel='noopener noreferrer'
                                href='https://www.instagram.com/rajnykdhulapkar/'
                            >
                                <AiFillInstagram />
                            </a>
                            <a
                                target='_blank'
                                rel='noopener noreferrer'
                                href='https://github.com/RajNykDhulapkar'
                            >
                                <AiFillGithub />
                            </a>
                            <a
                                target='_blank'
                                rel='noopener noreferrer'
                                href='https://blog.rajnykdhulapkar.me/'
                            >
                                <AiFillBulb />
                            </a>
                        </div>
                    </div>
                </section>
                <section>
                    <div>
                        <h3 className='text-3xl py-1 dark:text-white '>Services I offer</h3>
                        <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
                            Since the beginning of my journey as a freelance designer and developer,
                            I&apos;ve done remote work for
                            <span className='text-teal-500'> agencies </span>
                            consulted for <span className='text-teal-500'>startups </span>
                            and collaborated with talented people to create digital products for
                            both business and consumer use.
                        </p>
                        <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
                            I offer from a wide range of services, including brand design,
                            programming and teaching.
                        </p>
                    </div>
                    <div className='lg:flex gap-10'>
                        <div className='text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1'>
                            <Image src={design} alt='design' width={100} height={100} />
                            <h3 className='text-lg font-medium pt-8 pb-2  '>Beautiful Designs</h3>
                            <p className='py-2'>
                                Creating elegant designs suited for your needs following core design
                                theory.
                            </p>
                            <h4 className='py-4 text-teal-600'>Design Tools I Use</h4>
                            <p className='text-gray-800 py-1'>Photoshop</p>
                            <p className='text-gray-800 py-1'>Illustrator</p>
                            <p className='text-gray-800 py-1'>Figma</p>
                            <p className='text-gray-800 py-1'>Indesign</p>
                        </div>
                        <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
                            <Image src={code} alt='code' width={100} height={100} />
                            <h3 className='text-lg font-medium pt-8 pb-2 '>
                                Code your dream project
                            </h3>
                            <p className='py-2'>
                                Do you have an idea for your next great website? Let&apos;s make it
                                a reality.
                            </p>
                            <h4 className='py-4 text-teal-600'>Design Tools I Use</h4>
                            <p className='text-gray-800 py-1'>Photoshop</p>
                            <p className='text-gray-800 py-1'>Illustrator</p>
                            <p className='text-gray-800 py-1'>Figma</p>
                            <p className='text-gray-800 py-1'>Indesign</p>
                        </div>
                        <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
                            <Image src={consulting} alt='consulting' width={100} height={100} />
                            <h3 className='text-lg font-medium pt-8 pb-2 '>Consulting</h3>
                            <p className='py-2'>
                                Are you interested in feedback for your current project? I can give
                                you tips and tricks to level it up.
                            </p>
                            <h4 className='py-4 text-teal-600'>Design Tools I Use</h4>
                            <p className='text-gray-800 py-1'>Photoshop</p>
                            <p className='text-gray-800 py-1'>Illustrator</p>
                            <p className='text-gray-800 py-1'>Figma</p>
                            <p className='text-gray-800 py-1'>Indesign</p>
                        </div>
                    </div>
                </section>
                <section className='py-10'>
                    <div>
                        <h3 className='text-3xl py-1 dark:text-white '>Portofolio</h3>
                        <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
                            Since the beginning of my journey as a freelance designer and developer,
                            I&apos;ve done remote work for
                            <span className='text-teal-500'> agencies </span>
                            consulted for <span className='text-teal-500'>startups </span>
                            and collaborated with talented people to create digital products for
                            both business and consumer use.
                        </p>
                        <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
                            I offer from a wide range of services, including brand design,
                            programming and teaching.
                        </p>
                    </div>
                    <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
                        <div className='basis-1/3 flex-1 '>
                            <Image
                                className='rounded-lg object-cover'
                                alt='web1'
                                width={"100%"}
                                height={"100%"}
                                layout='responsive'
                                src={web1}
                            />
                        </div>
                        <div className='basis-1/3 flex-1'>
                            <Image
                                className='rounded-lg object-cover'
                                alt='web2'
                                width={"100%"}
                                height={"100%"}
                                layout='responsive'
                                src={web2}
                            />
                        </div>
                        <div className='basis-1/3 flex-1'>
                            <Image
                                className='rounded-lg object-cover'
                                alt='web3'
                                width={"100%"}
                                height={"100%"}
                                layout='responsive'
                                src={web3}
                            />
                        </div>
                        <div className='basis-1/3 flex-1'>
                            <Image
                                className='rounded-lg object-cover'
                                alt='web4'
                                width={"100%"}
                                height={"100%"}
                                layout='responsive'
                                src={web4}
                            />
                        </div>
                        <div className='basis-1/3 flex-1'>
                            <Image
                                className='rounded-lg object-cover'
                                alt='web5'
                                width={"100%"}
                                height={"100%"}
                                layout='responsive'
                                src={web5}
                            />
                        </div>
                        <div className='basis-1/3 flex-1'>
                            <Image
                                className='rounded-lg object-cover'
                                alt='web6'
                                width={"100%"}
                                height={"100%"}
                                layout='responsive'
                                src={web6}
                            />
                        </div>
                    </div>
                </section>
            </main>
        </div>
    );
}
